name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'
        cache: true

    - name: Run tests
      run: make test

    - name: Build binaries
      run: |
        # Linux AMD64
        GOOS=linux GOARCH=amd64 go build -o bin/forgottenserver-graphql-api-linux-amd64 ./cmd/server

        # Linux ARM64
        GOOS=linux GOARCH=arm64 go build -o bin/forgottenserver-graphql-api-linux-arm64 ./cmd/server

        # Windows AMD64
        GOOS=windows GOARCH=amd64 go build -o bin/forgottenserver-graphql-api-windows-amd64.exe ./cmd/server

        # macOS AMD64
        GOOS=darwin GOARCH=amd64 go build -o bin/forgottenserver-graphql-api-darwin-amd64 ./cmd/server

        # macOS ARM64 (Apple Silicon)
        GOOS=darwin GOARCH=arm64 go build -o bin/forgottenserver-graphql-api-darwin-arm64 ./cmd/server

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          bin/forgottenserver-graphql-api-linux-amd64
          bin/forgottenserver-graphql-api-linux-arm64
          bin/forgottenserver-graphql-api-windows-amd64.exe
          bin/forgottenserver-graphql-api-darwin-amd64
          bin/forgottenserver-graphql-api-darwin-arm64
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
